// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config({ path: ".env.local" });
dotenv.config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  generator: {
    name: "client",
    provider: "prisma-client-js",
    output: "src/generated/prisma",
    engineType: "node",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
